<a href="https://colab.research.google.com/github/axel-sirota/operations-arrays-numpy/blob/main/module3/OperationsNumpy_Mod3Demo2_Strides.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Strides on Numpy

## Prep

Let's recall how to access data in lists. For that we will leverage the dtaset for this course, whch is the results of an actual beheivoural experiment conducted by Universidad de la Matanza (UNLaM)

In [1]:
%%writefile get_data.sh
if [ ! -f dataset.csv ]; then
  wget -O dataset.csv https://www.dropbox.com/s/9t5lc04vxwvjvo6/dataset.csv?dl=0
fi

Writing get_data.sh


In [2]:
!bash get_data.sh


--2023-02-20 21:07:31--  https://www.dropbox.com/s/9t5lc04vxwvjvo6/dataset.csv?dl=0
Resolving www.dropbox.com (www.dropbox.com)... 162.125.8.18, 2620:100:601b:18::a27d:812
Connecting to www.dropbox.com (www.dropbox.com)|162.125.8.18|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: /s/raw/9t5lc04vxwvjvo6/dataset.csv [following]
--2023-02-20 21:07:32--  https://www.dropbox.com/s/raw/9t5lc04vxwvjvo6/dataset.csv
Reusing existing connection to www.dropbox.com:443.
HTTP request sent, awaiting response... 302 Found
Location: https://ucccdfe8bf589a18afc612d830e4.dl.dropboxusercontent.com/cd/0/inline/B266zQWOA9HwFzSZwsmnaius5zuEMEeYKuYKXf5zQQWa3J2xs4GFRSWHmDzF_BThRkfhEjV9iXtvJtlsQFU0q5wlozaQ-Sf5L-6jIa_PtDgGksJPMLc8a5o0b9crNeTkmyqzF4ywqdcDK1BvI4pvmOATdnNU9HJAL2GDvUUcc4jzpA/file# [following]
--2023-02-20 21:07:32--  https://ucccdfe8bf589a18afc612d830e4.dl.dropboxusercontent.com/cd/0/inline/B266zQWOA9HwFzSZwsmnaius5zuEMEeYKuYKXf5zQQWa3J2xs4GFRSWHmDzF_BThRkfhEjV9iXtvJt

In [3]:
import numpy as np

In [4]:
numpy_arr = np.genfromtxt('dataset.csv', delimiter=',')

## Strides

Sometimes you want to fetch values "every X times". for that we can use strides

In [7]:
# Fetch every two rows, the second column
numpy_arr[::2,1]

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 2., 2., 2.,
       2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2.,
       2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2.])

Let's check indeed the amount of elements is OK

In [10]:
print(f'The amount of elements in the second column is: {len(numpy_arr[:,1])}')
print(f'The amount of elements in the second column every two is: {len(numpy_arr[::2,1])}')

The amount of elements in the second column is: 199
The amount of elements in the second column every two is: 100


Effectively we did every two. In general the pattern is the following, **for each dimension**

In [12]:
numpy_arr[
    2    # Start value in the axis 0. This is the third value
    :
    54   # End value in the axis 0. This is the fifty-third value
    :
    3    # Stride. This is every 3 elements
    ,    # End of slice for axis 0 
    1    # In axis 1 we get just the second column
]

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 1., 1., 1., 1., 1.,
       1.])

However we can do this in every dimension, for example we can get every two columns, every three rows

In [14]:
arr = numpy_arr[
    :
    :
    3
    ,
    :
    :
    2
]


In [15]:
print(f'The shape of the new array is {arr.shape}')

The shape of the new array is (67, 6)


Notice that we get half the columns and a third of the rows, so we did OK.



## Dimensional indexing

Notice we can do this in any dimenision, it is not restricted to matrix like data. For this let's reshape our dataset and slice it!

In [29]:
numpy_arr[:100,:100].shape

(100, 11)

In [30]:
dim_view = numpy_arr[:100,:100].reshape(5,5,4,11)
dim_view

array([[[[ 0.  ,  0.  ,  2.  , ...,  3.  ,  2.67,  1.67],
         [ 1.  ,  0.  ,  4.  , ...,  2.  ,  2.33, -0.33],
         [ 2.  ,  0.  ,  3.  , ...,  4.  ,  4.  ,  2.33],
         [ 3.  ,  0.  ,  2.  , ...,  5.  ,  4.67,  3.33]],

        [[ 4.  ,  0.  ,  3.  , ...,  5.  ,  4.33,  2.  ],
         [ 5.  ,  0.  ,  2.  , ...,  4.  ,  4.  ,  2.67],
         [ 6.  ,  0.  ,  3.  , ...,  2.  ,  2.33,  0.  ],
         [ 7.  ,  0.  ,  4.  , ...,  3.  ,  3.33,  1.67]],

        [[ 8.  ,  0.  ,  2.  , ...,  3.  ,  3.  ,  1.67],
         [ 9.  ,  0.  ,  3.  , ...,  5.  ,  4.  ,  2.  ],
         [10.  ,  0.  ,  3.  , ...,  5.  ,  4.33,  3.  ],
         [11.  ,  0.  ,  2.  , ...,  2.  ,  2.67,  1.67]],

        [[12.  ,  0.  ,  3.  , ...,  4.  ,  3.33,  1.67],
         [13.  ,  0.  ,  2.  , ...,  3.  ,  2.  ,  0.67],
         [14.  ,  0.  ,  1.  , ...,  2.  ,  2.33,  1.33],
         [15.  ,  0.  ,  3.  , ...,  5.  ,  4.67,  3.33]],

        [[16.  ,  0.  ,  4.  , ...,  5.  ,  4.67,  3.  ],
      

In [33]:
dim_view[:,:,2:4:2, 10]  # What is this doing? Stop the video and think about it!

array([[[ 2.33],
        [ 0.  ],
        [ 3.  ],
        [ 1.33],
        [ 1.33]],

       [[ 1.67],
        [ 0.67],
        [  nan],
        [-0.67],
        [ 0.67]],

       [[ 0.67],
        [ 1.  ],
        [-0.33],
        [ 0.33],
        [ 0.33]],

       [[ 0.  ],
        [-0.33],
        [ 0.  ],
        [ 1.  ],
        [ 1.  ]],

       [[ 0.  ],
        [ 0.33],
        [ 0.33],
        [ 0.  ],
        [ 1.33]]])

It still works!