<a href="https://colab.research.google.com/github/axel-sirota/operations-arrays-numpy/blob/main/module4/OperationsNumpy_Mod4Demo2_LinearAlgebra.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Arithmetic on Numpy

## Prep

Let's recall how to access data in lists. For that we will leverage the dtaset for this course, whch is the results of an actual beheivoural experiment conducted by Universidad de la Matanza (UNLaM)

In [38]:
%%writefile get_data.sh
if [ ! -f dataset.csv ]; then
  wget -O dataset.csv https://www.dropbox.com/s/9t5lc04vxwvjvo6/dataset.csv?dl=0
fi

Overwriting get_data.sh


In [39]:
!bash get_data.sh


In [40]:
import numpy as np

In [41]:
numpy_arr = np.genfromtxt('dataset.csv', delimiter=',')

## Basic Linear Algebra

Given two Numpy arrays, we can also do classical Matrix multiplication and addition.

In [47]:
a = numpy_arr[2:6, 7:11]
b = numpy_arr[23:27, 3:7]

In [48]:
print(f'a shape is {a.shape} and b shape is {b.shape}')

a shape is (4, 4) and b shape is (4, 4)


In [49]:
a + b

array([[4.  , 6.  , 6.  , 6.33],
       [5.  , 6.  , 6.34, 6.33],
       [4.  , 8.  , 6.66, 7.  ],
       [3.  , 6.  , 6.33, 6.67]])

In [50]:
a.dot(b)  # Remember a * b is elementwise

array([[ 4.    , 28.66  , 29.4289, 57.32  ],
       [ 5.    , 33.67  , 34.99  , 67.67  ],
       [ 5.    , 29.99  , 31.0989, 60.65  ],
       [ 4.    , 27.34  , 28.2211, 54.68  ]])

Let's verify it is indeed the matrix multiplication because it will fails if the dimensions rule doesn't comply 

In [51]:
b = numpy_arr[23:26, 3:7]
b.shape

(3, 4)

In [52]:
a.dot(b)

ValueError: ignored

In [53]:
b.dot(a)

array([[28.    , 36.    , 34.    , 21.34  ],
       [23.68  , 29.35  , 27.9011, 17.01  ],
       [36.32  , 46.65  , 44.0989, 28.    ]])

Indeed it is matrix multiplication

## Solving a linear system

In numpy we can do the normal linear algebra operations. For example, we can solve the system:

```
A*x = b
```
Where the shapes are:
```
A -> (n,m)
x -> (m, 1)
b -> (m,1)
```

In [61]:
A = numpy_arr[5:10, 5:10].reshape(5,5)
b = numpy_arr[6, 5:10].reshape(5,1)

In [62]:
print(f'A shape is {A.shape} and b shape is {b.shape}')

A shape is (5, 5) and b shape is (5, 1)


In [63]:
x = np.linalg.inv(A).dot(b)

In [64]:
x

array([[   2.01515152],
       [-161.26020202],
       [-161.81691919],
       [-162.05363636],
       [ 484.9040404 ]])